name: Snyk Security

on:
  workflow_dispatch: # run manually
  # you could also add:
  # push:
  # pull_request:

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Example for Node.js (uncomment if your project needs it)
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      - name: Run Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Upload Snyk Code results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
